//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class customerAccount
    {
        public int Account_No { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string DOB { get; set; }
        public string Gender { get; set; }
        public string Marital_Status { get; set; }
        public string State_Of_Origin { get; set; }
        public string Mother_Maiden_Name { get; set; }
        public string Phone_No { get; set; }
        public string Email_Id { get; set; }
        public string Residential_Address { get; set; }
        public byte[] Picture { get; set; }
        public string Emergency_Name { get; set; }
        public string Emergency_No { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Date_Of_Registration { get; set; }
        public string Last_Edited { get; set; }
        public string Staff_On_Duty { get; set; }
        public int Id { get; set; }
    }
}
