//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposit
    {
        public int Serial_No { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public Nullable<decimal> Previous_Balance { get; set; }
        public Nullable<int> Account_No { get; set; }
        public string Deposit_Type { get; set; }
        public Nullable<decimal> Deposit_Amount { get; set; }
        public string Depositor_Name { get; set; }
        public string Depositor_Phone_No { get; set; }
        public string Staff_On_Duty { get; set; }
        public string Cheque_No { get; set; }
        public string Date_Of_Deposit { get; set; }
    }
}
