//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Withdrawal
    {
        public int Serial_No { get; set; }
        public Nullable<int> Account_No { get; set; }
        public string Name { get; set; }
        public string Phone_No { get; set; }
        public Nullable<decimal> Previous_Balance { get; set; }
        public string Withdrawal_Type { get; set; }
        public Nullable<decimal> Withdrawal_Amount { get; set; }
        public string Date_Of_Withrawal { get; set; }
        public string Staff_On_Duty { get; set; }
        public string Cheque_No { get; set; }
        public string Cheque_Bearer { get; set; }
        public Nullable<int> Withdrawal_Slip_No { get; set; }
        public byte[] Cheque_Bearer_Picture { get; set; }
    }
}
